# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: null
        # improves the security of the cookies used for sessions
        cookie_secure: auto

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
