language: php

services:
  - mysql

php:
  - 7.1
  - 7.3

env:
  - DB=mysql SYMFONY_ENV=travis

install:
  - composer install
  - php app/console propel:build
  - npm install -g bower polymer-cli@"^1.6.0"
  - cd src/Rotalia/FrontendBundle/Resources/source/
  - bower install
  - polymer build
  - cd $TRAVIS_BUILD_DIR
  # Propel
  - php app/console propel:database:create
  - php app/console propel:sql:insert --force

script:
  - vendor/bin/phpunit -c app/ src
