language: php

php:
  - 7.1

env:
  - SYMFONY_VERSION="2.8.2" DB=mysql

install:
  - composer install
  - php app/console propel:build
  - npm install -g bower polymer-cli@"^1.6.0"
  - cd src/Rotalia/FrontendBundle/Resources/source/
  - bower install
  - polymer build
  - cd $TRAVIS_BUILD_DIR
#  - php app/console propel:mig:mig -y

script:
  - phpunit -c app/
