language: php

php:
  - 7.1

env:
  - SYMFONY_VERSION="2.8.2" DB=mysql DB_USER=root

install:
  - composer install
  - php app/console propel:build
  - npm install -g bower polymer-cli@next
  - cd src/Rotalia/FrontendBundle/Resources/source/
  - bower prune
  - bower install
  - bower update
  - polymer build
  # Propel
  - php app/console propel:database:drop
  - php app/console propel:database:create
  - php app/console propel:sql:insert

