rotalia_frontend:
    resource: "@RotaliaFrontendBundle/Resources/config/routing.yml"
    prefix:   /fe/

#rotalia_user:
#    resource: "@RotaliaUserBundle/Resources/config/routing.yml"
#    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: RotaliaInventoryBundle:Home:home }

rotalia_inventory:
    resource: "@RotaliaInventoryBundle/Resources/config/routing.yml"
    prefix:   /

rotalia_api:
    resource: "@RotaliaAPIBundle/Resources/config/routing.yml"
    prefix:   /api/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#logout:
#    path:   /logout
#login:
#    path:     /login
#    defaults: { _controller: RotaliaInventoryBundle:Security:login }
#login_check:
#    path: /login_check