security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider # todo: use security.csrf.token_manager
            user_checker: ~
            remember_me:
                secret:      "%secret%"
                user_providers: [fos_userbundle]
                remember_me_parameter: rememberMe
                always_remember_me: true
            logout:
                invalidate_session: true
                delete_cookies:     ~
            anonymous:    true

    access_control:
        - { path: ^/api/authentication, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/kassa, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/tooted, role: ROLE_ADMIN }
        - { path: ^/krediit, role: ROLE_ADMIN }
        - { path: ^/kassad, role: ROLE_ADMIN }
        - { path: ^/tehingud, role: ROLE_ADMIN }

    providers:
        fos_userbundle:
            id: rotalia_user_provider

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    encoders:
        Rotalia\UserBundle\Model\User:
            id: rotalia_password_encoder
