security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider # todo: use security.csrf.token_manager
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 1 year in seconds
                path:     /
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/kassa, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/tooted, role: ROLE_ADMIN }
        - { path: ^/krediit, role: ROLE_ADMIN }
        - { path: ^/kassad, role: ROLE_ADMIN }
        - { path: ^/tehingud, role: ROLE_ADMIN }

    providers:
        fos_userbundle:
            id: rotalia_user_provider

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    encoders:
        Rotalia\UserBundle\Model\User:
            id: rotalia_password_encoder
