rotalia_frontend_homepage:
    path:     /
    defaults: { _controller: RotaliaFrontendBundle:Home:index}

rotalia_frontend_common:
    path:     /{path}.{extencion}
    defaults: { _controller: RotaliaFrontendBundle:Home:common}
    requirements:
            path: .+