authentication:
    resource: "@RotaliaAPIBundle/Resources/config/routing/authentication.yml"

product:
    resource: "@RotaliaAPIBundle/Resources/config/routing/product.yml"

pointOfSale:
    resource: "@RotaliaAPIBundle/Resources/config/routing/pointOfSale.yml"

productGroups:
    resource: "@RotaliaAPIBundle/Resources/config/routing/productGroups.yml"

reports:
    resource: "@RotaliaAPIBundle/Resources/config/routing/reports.yml"

setting:
    resource: "@RotaliaAPIBundle/Resources/config/routing/setting.yml"

member:
    resource: "@RotaliaAPIBundle/Resources/config/routing/member.yml"

transfer:
    resource: "@RotaliaAPIBundle/Resources/config/routing/transfer.yml"

creditNettings:
    resource: "@RotaliaAPIBundle/Resources/config/routing/creditNettings.yml"

RotaliaAPI_purchasePayment:
    pattern:  /purchase/{payment}/
    defaults: { _controller: RotaliaInventoryBundle:Purchase:Payment }
    methods: [POST]
    options:
        expose: true