parameters:
    mail_fetcher.class: Rotalia\APIBundle\Components\EmailFetchClient

services:
    rotalia.mail_fetcher:
        class: "%mail_fetcher.class%"
        arguments:
            - "%mail_fetcher.server_path%"
            - "%mail_fetcher.port%"
            - "%mail_fetcher.service%"
            - "%mail_fetcher.username%"
            - "%mail_fetcher.password%"
            - "%mail_fetcher.mailbox%"