parameters:
    rotalia.security.authentication.listener.migrate_old_password: false
    rotalia.security.authentication.listener.erase_credentials: true
    # Do not erase credentials so that AuthenticationEvent contains raw password for password plugin migration
    security.authentication.manager.erase_credentials: false

services:
    rotalia_password_encoder_plain:
        class: Rotalia\UserBundle\Security\RotaliaPasswordEncoderPropel
        arguments: ['plain']
    rotalia_password_encoder_old:
        class: Rotalia\UserBundle\Security\RotaliaPasswordEncoderPropel
        arguments: ['mysql_old_password']
    rotalia_password_encoder_native:
        class: Rotalia\UserBundle\Security\RotaliaPasswordEncoderPropel
        arguments: ['mysql_native_password']
    rotalia_security_authentication_listener:
        class: Rotalia\UserBundle\Security\AuthenticationListener
        arguments:
            - '@security.encoder_factory'
            - '%rotalia.security.authentication.listener.migrate_old_password%'
            - '%rotalia.security.authentication.listener.erase_credentials%'
        tags:
            - { name: "kernel.event_listener", event: "security.authentication.success", method: "onAuthenticationSuccess" }
    rotalia_user_provider:
        class: Rotalia\UserBundle\Security\UserProvider
        arguments: ["@fos_user.user_manager"]
