parameters:
    rotalia_password_encoder.plugin: 'old_password'

services:
    rotalia_password_encoder:
        class: Rotalia\UserBundle\Security\RotaliaPasswordEncoder
        arguments: ["%rotalia_password_encoder.plugin%"]
    rotalia_user_provider:
        class: Rotalia\UserBundle\Security\UserProvider
        arguments: ["@fos_user.user_manager"]
