services:
    rotalia_password_encoder:
        class: Rotalia\UserBundle\Security\RotaliaPasswordEncoder
    rotalia_user_provider:
        class: Rotalia\UserBundle\Security\UserProvider
        arguments: ["@fos_user.user_manager"]
