security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            json_login:
                check_path: json_login
                username_path: username
                password_path: password
                # Return JSend response when authentication fails
                failure_handler: 'Rotalia\API\Services\Security\AuthenticationFailureHandler'
                remember_me: true
            logout:
                invalidate_session: false
                delete_cookies:     ~

    access_control:
        - { path: ^/api/authentication, roles: PUBLIC_ACCESS }
#        - { path: ^/api/purchase, roles: PUBLIC_ACCESS }
#        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }
#        - { path: ^/kassa, role: PUBLIC_ACCESS }
#        - { path: ^/login$, role: PUBLIC_ACCESS }
#        - { path: ^/tooted, role: ROLE_ADMIN }
#        - { path: ^/krediit, role: ROLE_ADMIN }
#        - { path: ^/kassad, role: ROLE_ADMIN }
#        - { path: ^/tehingud, role: ROLE_ADMIN }

    # EntityUserProvider
    providers:
        users:
            entity:
                # the class of the entity that represents users
                class: 'App\Entity\User'
                # the property to query by - e.g. email, username, etc
                property: 'username'

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # User->getPlugin() determines which hasher is used
    password_hashers:
        plain:
            id: 'Rotalia\API\Services\Security\PlainTextPasswordHasher'
        mysql_old_password:
            id: 'Rotalia\API\Services\Security\MySqlOldPasswordHasher'
        mysql_native_password:
            id: 'Rotalia\API\Services\Security\MySqlPasswordHasher'
