# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/App/'
        exclude:
            - '../src/App/Extensions' # skip autowiring for extensions
    Rotalia\FrontendBundle\:
        resource: '../src/Rotalia/FrontendBundle'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Rotalia\API\:
        resource: '../src/Rotalia/API'
        exclude:
            - '../src/Rotalia/API/Tests'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Add customer loader to persist entities after each file
    rotalia.DoctrineOrmLoader:
        class: 'App\Extensions\Hautelook\AliceBundle\Loader\DoctrineOrmLoader'
        arguments:
            $bundleResolver: '@hautelook_alice.resolver.bundle'
            $fixtureLocator: '@hautelook_alice.locator'
            $purgeLoader: '@hautelook_alice.data_fixtures.purge_loader'
            $appendLoader: '@hautelook_alice.data_fixtures.append_loader'
            $logger: '@logger'

    hautelook_alice.loader.doctrine_orm_loader: '@rotalia.DoctrineOrmLoader'

imports:
    - { resource: 'parameters.yaml' }
    - { resource: 'security.yaml' }
