RotaliaReport_list:
    pattern:  /aruanded/
    defaults: { _controller: RotaliaInventoryBundle:Report:List, update: 0 }

RotaliaReport_view:
    pattern:  /aruanne/vaata/{id}/
    defaults: { _controller: RotaliaInventoryBundle:Report:View }

RotaliaReport_update:
    pattern:  /aruanne/majandus/
    defaults: { _controller: RotaliaInventoryBundle:Report:Update, id: null }

RotaliaReport_edit:
    pattern:  /aruanne/muuda/{id}/
    defaults: { _controller: RotaliaInventoryBundle:Report:Update }

RotaliaReport_browse:
    pattern:  /sirvi/{page}/
    defaults: { _controller: RotaliaInventoryBundle:Report:Browse }

RotaliaInventory_list:
    pattern:  /tooted
    defaults: { _controller: RotaliaInventoryBundle:Inventory:List }

RotaliaInventory_edit:
    pattern:  /tooted/muuda/{id}/
    defaults: { _controller: RotaliaInventoryBundle:Inventory:edit, id: null }

RotaliaInventory_add:
    pattern:  /tooted/lisa/
    defaults: { _controller: RotaliaInventoryBundle:Inventory:edit, id: null }


RotaliaInventory_removeItem:
    pattern:  /tooted/eemalda/{id}/
    defaults: { _controller: RotaliaInventoryBundle:Inventory:BuyItem }

RotaliaInventory_addItem:
    pattern:  /tooted/lisa/{id}/
    defaults: { _controller: RotaliaInventoryBundle:Inventory:AddItem }

#Stats
RotaliaInventory_statsProducts:
    pattern:  /stats/tooted/
    defaults: { _controller: RotaliaInventoryBundle:Stats:Products }

#Transactions
RotaliaInventory_purchaseLog:
    pattern:  /tehingud/
    defaults: { _controller: RotaliaInventoryBundle:Transactions:Log }

RotaliaInventory_purchaseLogMember:
    pattern:  /tehingud/liige/{memberId}/
    defaults: { _controller: RotaliaInventoryBundle:Transactions:Log }

RotaliaInventory_purchaseLogFilter:
    pattern:  /tehingud/filter/
    defaults: { _controller: RotaliaInventoryBundle:Transactions:LogFilter }

#Search
RotaliaInventory_searchMember:
    pattern:  /otsi/kasutajat/
    defaults: { _controller: RotaliaInventoryBundle:Search:Member }

RotaliaInventory_searchProduct:
    pattern:  /otsi/toodet/
    defaults: { _controller: RotaliaInventoryBundle:Search:Product }

#CreditManagement
RotaliaInventory_creditManagementList:
    pattern:  /krediit/
    defaults: { _controller: RotaliaInventoryBundle:CreditManagement:List }

RotaliaInventory_creditManagementAdjust:
    pattern:  /krediit/muuda/
    defaults: { _controller: RotaliaInventoryBundle:CreditManagement:Adjust }
    methods: [POST]
    options:
        expose: true

#PointOfSale
RotaliaInventory_pointOfSaleList:
    pattern: /kassad/
    defaults: { _controller: RotaliaInventoryBundle:PointOfSale:List }

RotaliaInventory_pointOfSaleAdd:
    pattern: /kassad/lisa/
    defaults: { _controller: RotaliaInventoryBundle:PointOfSale:Add }

RotaliaInventory_pointOfSaleDelete:
    pattern: /kassad/kustuta/{id}/
    defaults: { _controller: RotaliaInventoryBundle:PointOfSale:Delete }

#Purchase
RotaliaInventory_purchasePos:
    pattern:  /kassa/
    defaults: { _controller: RotaliaInventoryBundle:Purchase:Home }

RotaliaInventory_purchasePayment:
    pattern:  /kassa/tehing/{payment}/
    defaults: { _controller: RotaliaInventoryBundle:Purchase:Payment }
    methods: [POST]
    options:
        expose: true

RotaliaInventory_productInfo:
    pattern:  /toode/info/
    defaults: { _controller: RotaliaInventoryBundle:Product:Info }
    options:
        expose: true