parameters:
    rotalia_inventory.twig.extension.class: Rotalia\InventoryBundle\Twig\RotaliaTwigExtension

services:
    rotalia_inventory.twig.extension:
        class: '%rotalia_inventory.twig.extension.class%'
        public: false
        tags:
            - { name: twig.extension }
