Rotalia\InventoryBundle\Model\Report:
    properties:
        cash:
            - NotBlank: ~
Rotalia\InventoryBundle\Model\Product:
    properties:
        name:
            - NotBlank: ~
        price:
            - NotBlank: ~
            - GreaterThanOrEqual: 0
        amount_type:
            - NotBlank: ~
        status:
            - NotBlank: ~
    getters:
        productGroupValid:
            - 'True':
                message: 'Tootegruppi pole olemas'
