RotaliaAPI_authentication_check:
    path:  /authentication/
    methods: [GET]
    defaults: { _controller: Rotalia\APIBundle\Controller\AuthenticationController::tokenAction }

RotaliaAPI_authentication_login:
    path:  /authentication/
    methods: [POST]
    defaults: { _controller: Rotalia\APIBundle\Controller\AuthenticationController::loginAction }

RotaliaAPI_authentication_logout:
    path:  /authentication/
    methods: [DELETE]
    defaults: { _controller: Rotalia\APIBundle\Controller\AuthenticationController::logoutAction }
