RotaliaAPI_pos_list:
    path:  /pointOfSales/
    methods: [GET]
    defaults: { _controller: Rotalia\APIBundle\Controller\PointOfSalesController::ListAction }

RotaliaAPI_pos_view:
    path:  /pointOfSales/{id}/
    methods: [GET]
    defaults: { _controller: Rotalia\APIBundle\Controller\PointOfSalesController::GetAction }

RotaliaAPI_products_create:
    path:  /pointOfSales/
    methods: [POST]
    defaults: { _controller: Rotalia\APIBundle\Controller\PointOfSalesController::PostAction }

RotaliaAPI_products_update:
    path:  /pointOfSales/{id}/
    methods: [PATCH]
    defaults: { _controller: Rotalia\APIBundle\Controller\PointOfSalesController::PatchAction }

RotaliaAPI_products_delete:
    path:  /pointOfSales/{id}/
    methods: [DELETE]
    defaults: { _controller: Rotalia\APIBundle\Controller\PointOfSalesController::DeleteAction }
