RotaliaAPI_products_get:
    path:  /products/{id}/
    methods: [GET]
    defaults: { _controller: Rotalia\APIBundle\Controller\ProductsController::GetAction }

RotaliaAPI_products_post:
    path:  /products/
    methods: [POST]
    defaults: { _controller: Rotalia\APIBundle\Controller\ProductsController::PostAction }

RotaliaAPI_products_patch:
    path:  /products/{id}/
    methods: [PATCH]
    defaults: { _controller: Rotalia\APIBundle\Controller\ProductsController::PatchAction }
