RotaliaAPI_products_list:
    pattern:  /products/
    methods: [GET]
    defaults: { _controller: RotaliaAPIBundle:Products:List }

RotaliaAPI_products_get:
    pattern:  /products/{id}/
    methods: [GET]
    defaults: { _controller: RotaliaAPIBundle:Products:Get }
