RotaliaAPI_productGroups_list:
    path:  /productGroups/
    methods: [GET]
    defaults: { _controller: Rotalia\APIBundle\Controller\ProductGroupsController::ListAction }

RotaliaAPI_productGroups_post:
    path:  /productGroups/
    methods: [POST]
    defaults: { _controller: Rotalia\APIBundle\Controller\ProductGroupsController::PostAction }

RotaliaAPI_productGroups_patch:
    path:  /productGroups/{id}/
    methods: [PATCH]
    defaults: { _controller: Rotalia\APIBundle\Controller\ProductGroupsController::PatchAction }
