RotaliaAPI_purchases_list:
    path:  /purchase/
    methods: [GET]
    defaults: { _controller: Rotalia\APIBundle\Controller\PurchasesController::ListAction }

RotaliaAPI_purchasePayment:
    path:  /purchase/{payment}/
    defaults: { _controller: Rotalia\APIBundle\Controller\PurchaseController::PaymentAction }
    methods: [POST]
    options:
        expose: true
