RotaliaAPI_transfer_list:
    pattern:  /transfers/
    methods: [GET]
    defaults: { _controller: RotaliaAPIBundle:Transfers:List }

RotaliaAPI_transfer_create:
    pattern:  /transfers/
    methods: [POST]
    defaults: { _controller: RotaliaAPIBundle:Transfers:Post }
